# Generated by Django 3.1.5 on 2021-01-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
