# Generated by Django 3.1.5 on 2021-01-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_loglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loglist',
            name='client',
        ),
        migrations.RemoveField(
            model_name='loglist',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='client',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=30),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Loglist',
        ),
    ]
